export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCEEDED = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCEEDED = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILURE';